namespace SharpEDRChecker
{
    class EDRData
    {
        public static string[] edrlist =
        {
                "activeconsole",
                "ADA-PreCheck",
                "ahnlab",
                "amsi.dll",
                "anti malware",
                "anti-malware",
                "antimalware",
                "anti virus",
                "anti-virus",
                "antivirus",
                "appsense",
                "attivo networks",
                "attivonetworks",
                "authtap",
                "avast",
                "avecto",
                "bitdefender",
                "blackberry",
                "canary",
                "carbonblack",
                "carbon black",
                "cb.exe",
                "check point",
                "ciscoamp",
                "cisco amp",
                "countercept",
                "countertack",
                "cramtray",
                "crssvc",
                "crowdstrike",
                "csagent",
                "csfalcon",
                "csshell",
                "cybereason",
                "cyclorama",
                "cylance",
                "cynet",
                "cyoptics",
                "cyupdate",
                "cyvera",
                "cyserver",
                "cytray",
                "darktrace",
                "deep instinct",
                "defendpoint",
                "defender",
                "eectrl",
                "elastic",
                "endgame",
                "f-secure",
                "forcepoint",
                "fortinet",
                "fireeye",
                "groundling",
                "GRRservic",
                "harfanglab",
                "inspector",
                "ivanti",
                "juniper networks",
                "kaspersky",
                "lacuna",
                "logrhythm",
                "malware",
                "malwarebytes",
                "mandiant",
                "mcafee",
                "morphisec",
                "msascuil",
                "msmpeng",
                "nissrv",
                "omni",
                "omniagent",
                "osquery",
                "Palo Alto Networks",
                "pgeposervice",
                "pgsystemtray",
                "privilegeguard",
                "procwall",
                "protectorservic",
                "qianxin",
                "qradar",
                "qualys",
                "rapid7",
                "redcloak",
                "red canary",
                "SanerNow",
                "sangfor",
                "secureworks",
                "securityhealthservice",
                "semlaunchsv",
                "sentinel",
                "sentinelone",
                "sepliveupdat",
                "sisidsservice",
                "sisipsservice",
                "sisipsutil",
                "smc.exe",
                "smcgui",
                "snac64",
                "somma",
                "sophos",
                "splunk",
                "srtsp",
                "symantec",
                "symcorpu",
                "symefasi",
                "sysinternal",
                "sysmon",
                "tanium",
                "tda.exe",
                "tdawork",
                "tehtris",
                "threat",
                "trellix",
                "tpython",
                "trend micro",
                "uptycs",
                "vectra",
                "watchguard",
                "wincollect",
                "windowssensor",
                "wireshark",
                "withsecure",
                "xagt.exe",
                "xagtnotif.exe"
        };
    }
}
